# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CadenceCodegen < Formula
  desc "A tool for analyzing Cadence smart contracts and generating code"
  homepage "https://github.com/outblock/cadence-codegen"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Outblock/cadence-codegen/releases/download/v0.0.1/cadence-codegen_Darwin_x86_64.tar.gz"
      sha256 "1d35ed55aa3da865ad08c6c9660f7f545331b92e1ba08880c24610b91eb4f0ba"

      def install
        bin.install "cadence-codegen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Outblock/cadence-codegen/releases/download/v0.0.1/cadence-codegen_Darwin_arm64.tar.gz"
      sha256 "d530b600323ab758e58e8ed4873f63ec671678bea9d9217d30a5c35d11b3ed94"

      def install
        bin.install "cadence-codegen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Outblock/cadence-codegen/releases/download/v0.0.1/cadence-codegen_Linux_x86_64.tar.gz"
        sha256 "477e1806519ebadf215627670636770a5074a3b1d5826e9d6dffd5be9261aaa0"

        def install
          bin.install "cadence-codegen"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Outblock/cadence-codegen/releases/download/v0.0.1/cadence-codegen_Linux_arm64.tar.gz"
        sha256 "e19b5ff263ef8ad15236cfc52ef89068867413f2607c782305af902732a9736e"

        def install
          bin.install "cadence-codegen"
        end
      end
    end
  end

  test do
    system "#{bin}/cadence-codegen --version"
  end
end
